main/urls.py
from os import name
from django.urls import path
from .views import (MainView, 
AboutView, 
FeedbackCreateView, 
FeedbackListView, 
FeedbackDetailsView, 
FeedbackUpdateView, 
FeedbackDeleteView, 
UserListAPIView, 
UserProfileListAPIView, 
FeedbackListAPIView, 
CommentListAPIView, 
CommentCreateAPIView, 
CommentAPIView, 
FeedbackAPICreateView, 
UserFeedbacksListAPIView, 
UserCommentsListAPIView, 
FeedbackDestroyAPIView,
CommentDestroyAPIView)

app_name = 'main'

urlpatterns = [
    path('main/', MainView.as_view(), name='main'),
    path('about/', AboutView.as_view(), name='about'),
    path('feedbacks/', FeedbackListView.as_view(),name='feedback-list'),
    path('feedback/create/', FeedbackCreateView.as_view(),name='feedback-create'),
    path('feedback/detail/<int:pk>/', FeedbackDetailsView.as_view(),name='feedback-details'),
    path('feedback/update/<int:pk>/', FeedbackUpdateView.as_view(),name='feedback-update'),
    path('feedback/delete/<int:pk>/', FeedbackDeleteView.as_view(),name='feedback-delete'),

    ####################################################################################################
    path('api/users/', UserListAPIView.as_view(), name='api-users-list'),
    path('api/user-profiles/', UserProfileListAPIView.as_view(), name='api-user-profiles-list'),
    path('api/feedbacks/', FeedbackListAPIView.as_view(), name='api-feedbacks-list'),
    path('api/comments/', CommentListAPIView.as_view(), name='api-comment-list'),
    path('api/comment/create/', CommentCreateAPIView.as_view(), name='api-comment-create'),
    path('api/comment/detail/<int:pk>/', CommentAPIView.as_view(), name='api-comment-detail'),
    path('api/feedback/create/', FeedbackAPICreateView.as_view(),name='api-feedback-create'),
    path('api/user/<int:pk>/feedbacks/', UserFeedbacksListAPIView.as_view(), name='api-users-feedback'),
    path('api/user/<int:pk>/comments/', UserCommentsListAPIView.as_view(), name='api-users-comment'),
    path('api/feedback/delete/<int:pk>/', FeedbackDestroyAPIView.as_view(), name='api-delete-feedback'),
    path('api/comment/delete/<int:pk>/', FeedbackDestroyAPIView.as_view(), name='api-delete-comment'),
]

reservation/urls.py
from django.urls import path
from .views import (ReservationAPICreateView, 
ReservationListView, 
ReservationCreateView, 
ReservationListAPIView, 
UserReservationListAPIView,
ReservationDestroyAPIView,
)

app_name = 'reservation'

urlpatterns = [
    path('reservation/',ReservationCreateView.as_view(),name='reservations'),
    path('orders/', ReservationListView.as_view(), name='orders'),

####################################################################################################

    path('api/reservations/',ReservationListAPIView.as_view(),name='api-reservations'),
    path('api/reservation/create/',ReservationAPICreateView.as_view(), name='api-reservation-create'),
    path('api/user/<int:pk>/reservations/', UserReservationListAPIView.as_view(), name='api-users-reservations'),
    path('api/reservation/delete/<int:pk>/', ReservationDestroyAPIView.as_view(), name='api-delete-reservation'),
]

tamak/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from main import views as main_views
from main.views import LogoutView, MainView, LoginView, RegistrationRestoView, LoginAPIView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('registration/', RegistrationRestoView.as_view(), name='registration'),
    path('login/', LoginView.as_view(template_name = 'main/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='main/logout.html'), name='logout'),
    path('',include('teams.urls')),
    path('',include('reservation.urls')),
    path('',include('menu.urls')),

####################################################################################################

    path('api-auth/', include('rest_framework.urls')),
    path('api/login/',LoginAPIView.as_view(), name='api-login'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservation/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.utils import timezone
from django.contrib.auth.models import User
from django.shortcuts import reverse

from main.models import UserProfile

AMOUNT_CHOICES=(
    ('1','1'),
    ('2','2'),
    ('3','3'),
    ('4','4'),
    ('5','5'),
    ('6','6')
)

class Reservation(models.Model):
    user = models.ForeignKey(
        to=UserProfile,
        on_delete=CASCADE,
        related_name='users'
    )

    phone_number = models.CharField(max_length=50)

    amount_of_users = models.CharField(
        choices=AMOUNT_CHOICES,
        max_length=15
        )

    date = models.DateField()

    time = models.TimeField()

    message = models.TextField()

    date_created_at = models.DateTimeField(default=timezone.now,editable=False)


    def get_absolute_url(self):
        return reverse("reservation:orders")

reservation/forms.py
from django import forms
from django.forms.models import ModelForm

from reservation.models import Reservation

class ReservationForm(ModelForm):
    class Meta:
        model = Reservation
        exclude = ['date_created_at','user']
        widgets = {
                'message': forms.Textarea(
                    attrs={
                        'cols': 35, 
                        'rows': 3
                    }
                ),
                'date': forms.DateInput(
                    attrs={
                        'class': 'form-control datetimepicker-input',
                        'data-target': '#datetimepicker4',
                        'placeholder':'Date',
                    }
                ),
                'time': forms.TimeInput(
                    attrs=
                    {
                        'class': 'form-control timepicker-input',
                        'data-target': '#datetimepicker3',
                        'placeholder':'Time',
                        'type': 'time'
                    }
                ),
                'amount_of_users': forms.Select(
                    attrs={
                        'class':'form-control',
                        'id':'selectPerson'
                    }
                )
        }

reservation/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, reverse
from django.views.generic import ListView, CreateView
from reservation.forms import ReservationForm

from reservation.models import Reservation
from main.models import UserProfile

####################################################################################################
####################################################################################################
from rest_framework.views import APIView
from rest_framework import status
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.response import Response
from rest_framework.generics import CreateAPIView, DestroyAPIView, UpdateAPIView

from .serializers import UserListSerializer

from.serializers import ReservationListSerializer, UserProfileListSerializer
####################################################################################################

class ReservationCreateView(LoginRequiredMixin, CreateView):
    model = Reservation
    template_name = 'reservation/reservation.html'
    

    def post(self, request):
        book_form = ReservationForm(request.POST)
        if book_form.is_valid():
            form = book_form.save(commit=False)
            user_form = User.objects.get(pk=request.user.pk)
            profile_values = UserProfile.objects.get(user = user_form)
            form.user = profile_values
            form.save()
            return redirect('reservation:orders')
        else:
            book_form = ReservationForm()

        return render(
            request=request,
            template_name='reservation/reservation.html',
            context={"form": book_form}
    )
    form_class = ReservationForm


class ReservationListView(LoginRequiredMixin,ListView):
    model = Reservation
    template_name = 'reservation/orders.html'
   

####################################################################################################
####################################################################################################
####################################################################################################

class ReservationListAPIView(APIView):
    permission_classes = (IsAuthenticated,)
    serializer_classes = ReservationListSerializer

    def get(self, request):
        reservations = Reservation.objects.all()
        serializer = self.serializer_classes(reservations, many=True)

        return Response(
            status=status.HTTP_200_OK,
            data=serializer.data
        )

class ReservationAPICreateView(CreateAPIView):
    permission_classes = (AllowAny,)
    serializer_class = ReservationListSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(
            status=status.HTTP_201_CREATED,
            data={
                'success': True,
                'message': "Reservation has been created successfuly!",
                'result': serializer.data,
            }
        )

class UserReservationListAPIView(APIView):
    permission_class = (AllowAny,)
    serializer_class = UserListSerializer

    def get(self, request, pk):
        user = User.objects.filter(pk=pk).first()

        if not user:
            return Response(
                status=status.HTTP_404_NOT_FOUND,
                data={
                    'success': False,
                    'result': 'User does not exist!'
                }
            )

        serializer = self.serializer_class(user)

        return Response(
            status=status.HTTP_200_OK,
            data={
                'success': True,
                'result': serializer.data
            }
        )

class ReservationDestroyAPIView(DestroyAPIView):
    permission_class = (AllowAny,)
    queryset = Reservation.objects.all()
    model = Reservation

reservation/templates/reservation/orders.html
{% extends 'main/wrapper.html' %}
{% load static %}
{% block content %}
<div class="container py-5">
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-10 col-md-12 col-sm-12">
            <div class="section-content">
                <div class="heading-section text-center">
                    <span class="subheading">
                        <h2>
                            История Бронирования
                        </h2>
                    </span>
                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="card text-center">
                <img src="{{ user.profile.profile_photo.url }}" alt="John" style="width:100%">
                <div class="mt-2">
                    <h1>{{ user.username }}</h1>
                    <p class="title">{{ user.email }}</p>
                    <p class="bg-dark w-100 text-light py-2 font-weight-bold">Всего Броней: {{ reservation_list|length}}
                    </p>
                    <div class="mb-3">
                        <a class="btn btn-primary" href="">Изменить Профиль</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-9">
            <div class="row">
            {% if reservation_list|length > 0 %}
            {% for reservation in reservation_list %}
            <div class="col-5 m-4">
                <div class="card mt-2 mx-1 shadow-sm text-center">
                    <div class="card-header">
                        <h4 class="my-0 fw-normal">{{ reservation.user }}</h4>
                    </div>
                    <div class="card-body font-weight-bold" style="height: 120px;">
                        <strong class="text-muted">Комментарий:</strong>
                        <h6 class="card-title pricing-card-title mt-2">
                            {{ reservation.message|truncatechars:60 }}
                        </h6>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4">
                            <li><span class="font-weight-bold">Время:</span> <strong>{{ reservation.time }}</strong>
                            </li>
                            <li><span class="font-weight-bold">Дата:</span> <strong>{{ reservation.date }}</strong>
                            </li>
                        </ul>
                    </div>
                    <div class>
                        <h5 class="bg-dark w-100 text-light py-2">Количество: {{ reservation.amount_of_users }}</h5>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <div class="container">
                <div class="row align-items-center" style="height: 500px;">
                    <p class="mx-auto" style="font-size: 300px; font-weight:bolder;">{{ reservation_list|length }}
                    </p>
                </div>
            </div>
            {% endif %}
        </div>
        </div>
    </div>
</div>
{% endblock content %}

reservation/templates/reservation/reservation.html
{% extends 'main/wrapper.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<section id="gtco-reservation" class="bg-fixed bg-white section-padding overlay"
    style="background-image: url({% static 'img/reservation-bg.jpg' %});">
    <div class="container">
        <div class="row">
            <div class="col-lg-5">
                <div class="section-content bg-white p-5 shadow">
                    <div class="heading-section text-center">
                        <h2>
                            <span class="subheading">
                                Resto Бронь
                            </span>
                        </h2>

                    </div>
                    <form method="POST" name="orders" class="text-center">
                        {% csrf_token %}
                        {{ form.errors }}
                        <div class="col-12 form-group">
                            <div class="col-12">
                                {{ form.phone_number.label_tag }}
                            </div>
                            <div class="col-12">
                                {{ form.phone_number }}
                            </div>
                        </div>

                        <div class="d-flex">
                            <div class="col-md-6 form-group px-0">
                                {{ form.date.label_tag }}
                                <div class="input-group date" id="datetimepicker4" data-target-input="nearest">
                                    {{ form.date }}
                                    <div class="input-group-append" data-target="#datetimepicker4"
                                        data-toggle="datetimepicker">
                                        <div class="input-group-text">
                                            <span class="lnr lnr-calendar-full"></span>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6 form-group px-0">
                                {{ form.time.label_tag }}
                                <div class="col-12 form-group">
                                    {{ form.time }}
                                </div>
                            </div>
                        </div>

                        <div class="col-12 form-group">
                            <div class="col-12">
                                {{ form.amount_of_users.label_tag }}
                            </div>
                            <div class="col-12 px-5">
                                {{ form.amount_of_users }}
                            </div>
                        </div>

                        <div class="col-12 form-group">
                            {{ form.message.label_tag }}
                            {{ form.message }}
                        </div>

                        <div class="text-center">
                            <div class="form-group">
                                <button class="btn btn-warning" type="submit" style="color: rgb(87, 79, 79);">
                                    <b>Бронировать</b></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>
</section>
{% endblock content %}