main/urls.py
from os import name
from django.urls import path
from .views import (MainView, 
AboutView, 
FeedbackCreateView, 
FeedbackListView, 
FeedbackDetailsView, 
FeedbackUpdateView, 
FeedbackDeleteView, 
UserListAPIView, 
UserProfileListAPIView, 
FeedbackListAPIView, 
CommentListAPIView, 
CommentCreateAPIView, 
CommentAPIView, 
FeedbackAPICreateView, 
UserFeedbacksListAPIView, 
UserCommentsListAPIView, 
FeedbackDestroyAPIView,
CommentDestroyAPIView)

app_name = 'main'

urlpatterns = [
    path('main/', MainView.as_view(), name='main'),
    path('about/', AboutView.as_view(), name='about'),
    path('feedbacks/', FeedbackListView.as_view(),name='feedback-list'),
    path('feedback/create/', FeedbackCreateView.as_view(),name='feedback-create'),
    path('feedback/detail/<int:pk>/', FeedbackDetailsView.as_view(),name='feedback-details'),
    path('feedback/update/<int:pk>/', FeedbackUpdateView.as_view(),name='feedback-update'),
    path('feedback/delete/<int:pk>/', FeedbackDeleteView.as_view(),name='feedback-delete'),

    ####################################################################################################
    path('api/users/', UserListAPIView.as_view(), name='api-users-list'),
    path('api/user-profiles/', UserProfileListAPIView.as_view(), name='api-user-profiles-list'),
    path('api/feedbacks/', FeedbackListAPIView.as_view(), name='api-feedbacks-list'),
    path('api/comments/', CommentListAPIView.as_view(), name='api-comment-list'),
    path('api/comment/create/', CommentCreateAPIView.as_view(), name='api-comment-create'),
    path('api/comment/detail/<int:pk>/', CommentAPIView.as_view(), name='api-comment-detail'),
    path('api/feedback/create/', FeedbackAPICreateView.as_view(),name='api-feedback-create'),
    path('api/user/<int:pk>/feedbacks/', UserFeedbacksListAPIView.as_view(), name='api-users-feedback'),
    path('api/user/<int:pk>/comments/', UserCommentsListAPIView.as_view(), name='api-users-comment'),
    path('api/feedback/delete/<int:pk>/', FeedbackDestroyAPIView.as_view(), name='api-delete-feedback'),
    path('api/comment/delete/<int:pk>/', FeedbackDestroyAPIView.as_view(), name='api-delete-comment'),
]

tamak/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from main import views as main_views
from main.views import LogoutView, MainView, LoginView, RegistrationRestoView, LoginAPIView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('registration/', RegistrationRestoView.as_view(), name='registration'),
    path('login/', LoginView.as_view(template_name = 'main/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='main/logout.html'), name='logout'),
    path('',include('teams.urls')),
    path('',include('reservation.urls')),
    path('',include('menu.urls')),

####################################################################################################

    path('api-auth/', include('rest_framework.urls')),
    path('api/login/',LoginAPIView.as_view(), name='api-login'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teams/urls.py
from django.urls import path

from .views import (CookAPICreateView, 
CookView, 
CookDetailView, 
CookListAPIView,
CookDestroyAPIView,
)

app_name = 'teams'

urlpatterns = [
    path('team/', CookView.as_view(), name='cook-list'),
    path('team/details/<int:pk>/', CookDetailView.as_view(), name='cook-detail'),

####################################################################################################

    path('api/cooks/',CookListAPIView.as_view(),name='api-cooks'),
    path('api/cook/create/',CookAPICreateView.as_view(), name='api-cook-create'),
    path('api/cook/delete/<int:pk>/', CookDestroyAPIView.as_view(), name='api-delete-cook'),
]

teams/models.py
from django.db import models
from django.contrib.auth.models import User

from main.models import UserProfile


COOK_EDUCATION = (
    ('University degree','University degree'),
    ('Specialized secondary education','Specialized secondary education'),
    ('Secondary education','Secondary education'),
    ('Without education','Without education')
)

class Cook(models.Model):
    cook_source = models.OneToOneField(
        to=UserProfile,
        on_delete=models.CASCADE,
    )

    work_experience = models.IntegerField()

    pass_work_place = models.TextField()

    education = models.CharField(
        choices=COOK_EDUCATION,
        default='University degree',
        max_length=40
    )

    def __str__(self) :
        return self.education

teams/forms.py
from django import forms
from django.forms.models import ModelForm

from .models import Cook

class CookForm(ModelForm):
    class Meta:
        model = Cook
        fields = ('cook_source',
                    'work_experience',
                    'pass_work_place',
                    'education',
                   'education',)

teams/views.py
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import ListView, CreateView
from django.views.generic.base import ContextMixin
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from main.models import UserProfile
from teams.forms import CookForm

from teams.models import Cook
from django.views import View

####################################################################################################
####################################################################################################
from rest_framework.views import APIView
from rest_framework import status
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.response import Response
from rest_framework.generics import CreateAPIView, DestroyAPIView, UpdateAPIView

from.serializers import CookListSerializer
####################################################################################################

class CookView(View):
    def get(self,request):
        username = Cook.objects.all()
        form = CookForm()
        return render(request=request,
            template_name = 'teams/team.html',
            context={'form':form,'cook_list':username}
        )
    def post(self, request):
        form = CookForm(request.POST)
        profile_id = request.POST.get('cook_source')
        cook = Cook.objects.filter(cook_source = profile_id)
        username = Cook.objects.all()
        if cook:
            return render(request=request,template_name='teams/team.html',context={'error':'Такой повар уже есть','cook_list':username})
        if form.is_valid():
            cook_form = form.save(commit=False)
            user_form = User.objects.get(pk=request.user.pk)
            profile_values = UserProfile.objects.get(user = user_form)
            cook_form.cook_source = profile_values
            cook_form.save()
            return redirect('teams:cook-list')
        else:
            form = CookForm()
            return render(request=request,template_name='teams/team.html',context={'form':form,'cook_list':username})
    


class CookDetailView(DetailView, LoginRequiredMixin):
    model = Cook
    template_name = 'teams/teams_details.html'
   

####################################################################################################
####################################################################################################
####################################################################################################


class CookListAPIView(APIView):
    permission_classes = (IsAuthenticated,)
    serializer_classes = CookListSerializer

    def get(self, request):
        cooks = Cook.objects.all()
        serializer = self.serializer_classes(cooks, many=True)

        return Response(
            status=status.HTTP_200_OK,
            data=serializer.data
        )

class CookAPICreateView(CreateAPIView):
    permission_classes = (AllowAny,)
    serializer_class = CookListSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(
            status=status.HTTP_201_CREATED,
            data={
                'success': True,
                'message': "Cook has been created successfuly!",
                'result': serializer.data,
            }
        )


class CookDestroyAPIView(DestroyAPIView):
    permission_class = (AllowAny,)
    queryset = Cook.objects.all()
    model = Cook

teams/templates/teams/team.html
{% extends 'main/wrapper.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container bg-white section-padding">
    <div class="container">
        <div class="section-content">
            <div class="heading-section text-center">
                <h2>
                    <span class="subheading">
                        Наша Команда
                    </span>
                </h2>
            </div>
            <div class="row">
                {% for member in cook_list %}
                <div class="col-4">
                    <div class="team-card mb-5">
                        <a href="{% url 'teams:cook-detail' member.pk %}">
                            <img src="{{ member.cook_source.profile_photo.url }}" width="400px" height="650px" alt="">
                        <div class="team-desc">
                            <h4 class="mb-0">{{ member }} {{ member.cook_source.last_name }}</h4>
                            <ul class="list-inline mb-0 team-social-links">
                                <li class="list-inline-item">
                                    <a href="#">
                                        <i class="fab fa-facebook-f"></i>
                                    </a>
                                </li>
                                <li class="list-inline-item">
                                    <a href="#">
                                        <i class="fab fa-twitter"></i>
                                    </a>
                                </li>
                                <li class="list-inline-item">
                                    <a href="#">
                                        <i class="fab fa-instagram"></i>
                                    </a>
                                </li>
                                <li class="list-inline-item">
                                    <a href="#">
                                        <i class="fab fa-google-plus-g"></i>
                                    </a>
                                </li>
                            </a>
                            </ul>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% if error %}
    <div class="text-center">
    <h3>
    <span class="subheading">
        {{ error }}
    </span>
    </h3>
    </div>
    {% else %}
    <div class="col-12 text-center">
        <form method="POST">
            {% csrf_token %}
            {% if user.is_superuser %}
            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#staticBackdrop"
                style="color: whitesmoke;">
                
                Добавить Персонал
                
            </button>
            {% endif %}

            <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
                aria-labelledby="staticBackdropLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="staticBackdropLabel">Форма добавления</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            {{ form|crispy }}
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-primary">Добавить</button>
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отменить</button>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
        </form>
    </div>
</div>
{% endblock content %}

teams/templates/teams/teams_details.html
{% extends 'main/wrapper.html' %}
{% block content %}
<div class="container bg-white section-padding">
    <div class="container">
        <div class="row justify-content-center text-center">
            <div class="col-4">
                <div class="team-card mb-5">
                    <img class="img-fluid" src="{{ object.cook_source.profile_photo.url }}" alt="">
                    <h4 class="mb-0">{{ object.first_name }} {{ object.last_name }}</h4>
                </div>
            </div>
            <div class="heading-section">
                <h2>
                    <span class="subheading">
                        {{ object.cook_source.user.first_name }} {{ object.cook_source.user.last_name }}
                    </span>
                </h2>
            </div>
            <div class="card" style="width: 18rem;">
                <div class="card-header">
                    <strong>Образование:<br>{{ object.education }}</strong>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><strong>Опыт работы:</strong> {{ object.work_experience }} лет</li>
                    <li class="list-group-item"><strong>История работы:</strong> {{ object.pass_work_place }}</li>
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock content %}