main/urls.py
from os import name
from django.urls import path
from .views import (MainView, 
AboutView, 
FeedbackCreateView, 
FeedbackListView, 
FeedbackDetailsView, 
FeedbackUpdateView, 
FeedbackDeleteView, 
UserListAPIView, 
UserProfileListAPIView, 
FeedbackListAPIView, 
CommentListAPIView, 
CommentCreateAPIView, 
CommentAPIView, 
FeedbackAPICreateView, 
UserFeedbacksListAPIView, 
UserCommentsListAPIView, 
FeedbackDestroyAPIView,
CommentDestroyAPIView)

app_name = 'main'

urlpatterns = [
    path('main/', MainView.as_view(), name='main'),
    path('about/', AboutView.as_view(), name='about'),
    path('feedbacks/', FeedbackListView.as_view(),name='feedback-list'),
    path('feedback/create/', FeedbackCreateView.as_view(),name='feedback-create'),
    path('feedback/detail/<int:pk>/', FeedbackDetailsView.as_view(),name='feedback-details'),
    path('feedback/update/<int:pk>/', FeedbackUpdateView.as_view(),name='feedback-update'),
    path('feedback/delete/<int:pk>/', FeedbackDeleteView.as_view(),name='feedback-delete'),

    ####################################################################################################
    path('api/users/', UserListAPIView.as_view(), name='api-users-list'),
    path('api/user-profiles/', UserProfileListAPIView.as_view(), name='api-user-profiles-list'),
    path('api/feedbacks/', FeedbackListAPIView.as_view(), name='api-feedbacks-list'),
    path('api/comments/', CommentListAPIView.as_view(), name='api-comment-list'),
    path('api/comment/create/', CommentCreateAPIView.as_view(), name='api-comment-create'),
    path('api/comment/detail/<int:pk>/', CommentAPIView.as_view(), name='api-comment-detail'),
    path('api/feedback/create/', FeedbackAPICreateView.as_view(),name='api-feedback-create'),
    path('api/user/<int:pk>/feedbacks/', UserFeedbacksListAPIView.as_view(), name='api-users-feedback'),
    path('api/user/<int:pk>/comments/', UserCommentsListAPIView.as_view(), name='api-users-comment'),
    path('api/feedback/delete/<int:pk>/', FeedbackDestroyAPIView.as_view(), name='api-delete-feedback'),
    path('api/comment/delete/<int:pk>/', FeedbackDestroyAPIView.as_view(), name='api-delete-comment'),
]

menu/urls.py
from django.urls import path
from .views import (MenuListView, 
WineListView, 
WineListAPIView, 
PrimaryMealListAPIView, 
MealListAPIView, 
RateListAPIView, 
PrimaryMealAPICreateView, 
MealAPICreateView,
WineAPICreateView,
RateAPICreateView,
MealDestroyAPIView,
PrimaryMealDestroyAPIView,
WineDestroyAPIView,
RateDestroyAPIView
)


app_name = 'menu'

urlpatterns = [
    path('meals/',MenuListView.as_view(),name='meals'),
    path('wines/', WineListView.as_view(),name='wines'),

####################################################################################################

    path('api/wines/',WineListAPIView.as_view(),name='api-wines'),
    path('api/meals/',MealListAPIView.as_view(),name='api-meals'),
    path('api/primary-meals/',PrimaryMealListAPIView.as_view(),name='api-primary-meals'),
    path('api/rates/',RateListAPIView.as_view(),name='api-rates'),
    path('api/meal/primary/', PrimaryMealAPICreateView.as_view(), name='create-primary-meal'),
    path('api/meal/create/', MealAPICreateView.as_view(), name='create-meal'),
    path('api/rate/create/', RateAPICreateView.as_view(), name='create-rate'),
    path('api/wine/create/', WineAPICreateView.as_view(), name='create-wine'),
    path('api/rate/delete/<int:pk>/', RateDestroyAPIView.as_view(), name='api-delete-comment'),
    path('api/wine/delete/<int:pk>/', WineDestroyAPIView.as_view(), name='api-delete-comment'),
    path('api/primary-meal/delete/<int:pk>/', PrimaryMealDestroyAPIView.as_view(), name='api-delete-comment'),
    path('api/meal/delete/<int:pk>/', MealDestroyAPIView.as_view(), name='api-delete-meal'),
]

reservation/urls.py
from django.urls import path
from .views import (ReservationAPICreateView, 
ReservationListView, 
ReservationCreateView, 
ReservationListAPIView, 
UserReservationListAPIView,
ReservationDestroyAPIView,
)

app_name = 'reservation'

urlpatterns = [
    path('reservation/',ReservationCreateView.as_view(),name='reservations'),
    path('orders/', ReservationListView.as_view(), name='orders'),

####################################################################################################

    path('api/reservations/',ReservationListAPIView.as_view(),name='api-reservations'),
    path('api/reservation/create/',ReservationAPICreateView.as_view(), name='api-reservation-create'),
    path('api/user/<int:pk>/reservations/', UserReservationListAPIView.as_view(), name='api-users-reservations'),
    path('api/reservation/delete/<int:pk>/', ReservationDestroyAPIView.as_view(), name='api-delete-reservation'),
]

tamak/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from main import views as main_views
from main.views import LogoutView, MainView, LoginView, RegistrationRestoView, LoginAPIView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('registration/', RegistrationRestoView.as_view(), name='registration'),
    path('login/', LoginView.as_view(template_name = 'main/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='main/logout.html'), name='logout'),
    path('',include('teams.urls')),
    path('',include('reservation.urls')),
    path('',include('menu.urls')),

####################################################################################################

    path('api-auth/', include('rest_framework.urls')),
    path('api/login/',LoginAPIView.as_view(), name='api-login'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teams/urls.py
from django.urls import path

from .views import (CookAPICreateView, 
CookView, 
CookDetailView, 
CookListAPIView,
CookDestroyAPIView,
)

app_name = 'teams'

urlpatterns = [
    path('team/', CookView.as_view(), name='cook-list'),
    path('team/details/<int:pk>/', CookDetailView.as_view(), name='cook-detail'),

####################################################################################################

    path('api/cooks/',CookListAPIView.as_view(),name='api-cooks'),
    path('api/cook/create/',CookAPICreateView.as_view(), name='api-cook-create'),
    path('api/cook/delete/<int:pk>/', CookDestroyAPIView.as_view(), name='api-delete-cook'),
]

main/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class UserProfile(models.Model):
    user = models.OneToOneField(
        to=User,
        on_delete=models.CASCADE,
        related_name='profile',
    )

    profile_photo = models.ImageField(upload_to = 'users/profiles/', default = 'default.png')

    age = models.SmallIntegerField(default=0)

    favorite_anime = models.CharField(max_length=25,default='Unknown')

    def __str__(self):
        return '%s %s' % (self.user.first_name, self.user.last_name)


class Feedback(models.Model):
    author = models.ForeignKey(to=UserProfile,on_delete=models.CASCADE,related_name='authors')
    feedback_text = models.TextField()
    date_created = models.DateTimeField(default=timezone.now,editable=False)

    def get_absolute_url(self):
        return reverse("main:feedback-details", kwargs={"pk": self.pk})

    def __str__(self):
        return '%s' % self.feedback_text

class Comment(models.Model):
    author = models.ForeignKey(to=UserProfile, on_delete=models.CASCADE, related_name='comment_authors')
    assigned_to_feedback = models.ForeignKey(to=Feedback, on_delete=models.CASCADE, related_name='assigned_feedbacks')
    comment_text = models.TextField()
    date_created = models.DateTimeField(default=timezone.now,editable=False)

    def get_absolute_url(self):
        return reverse("main:feedback-details", kwargs={"pk": self.pk})

    def __str__(self):
        return '%s' % self.comment_text

main/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Feedback, Comment
from django.forms import ModelForm

class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.CharField(max_length=50)
    fields = (
        'first_name',
        'last_name',
        'email'
    )

class FeedbackCreateForm(ModelForm):
    class Meta:
        model = Feedback
        exclude = ['author', 'date_created']

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = 'comment_text',

main/templates/main/about.html
{% extends 'main/wrapper.html' %}
{% load static %}
{% block content %}
<section id="gtco-welcome" class="bg-white section-padding">
    <div class="container">
        <div class="section-content">
            <div class="row">
                <div class="col-sm-5 img-bg d-flex shadow align-items-center justify-content-center justify-content-md-end img-2" style="background-image: url({% static 'img/hero-2.jpg' %});">
                    
                </div>
                <div class="col-sm-7 py-5 pl-md-0 pl-4">
                    <div class="heading-section pl-lg-5 ml-md-5">
                        <span class="subheading">
                            О нас
                        </span>
                        <h2>
                            Добро пожаловать в Resto
                        </h2>
                    </div>
                    <div class="pl-lg-5 ml-md-5">
                        <p>On her way she met a copy. The copy warned the Little Blind Text, that where it came from it would have been rewritten a thousand times and everything that was left from its origin would be the word "and" and the Little Blind Text should turn around and return to its own, safe country. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
                        <h3 class="mt-5">Special Recipe</h3>
                        <div class="row">
                            <div class="col-4">
                                <a href="#" class="thumb-menu">
                                    <img class="img-fluid img-cover" src="{% static 'img/hero-1.jpg' %}" />
                                    <h6>Australian Organic Beef</h6>
                                </a>
                            </div>
                            <div class="col-4">
                                <a href="#" class="thumb-menu">
                                    <img class="img-fluid img-cover" src="{% static 'img/hero-2.jpg' %}" />
                                    <h6>Australian Organic Beef</h6>
                                </a>
                            </div>
                            <div class="col-4">
                                <a href="#" class="thumb-menu">
                                    <img class="img-fluid img-cover" src="{% static 'img/hero-3.jpg' %}"/>
                                    <h6>Australian Organic Beef</h6>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

main/templates/main/feedback_create.html
{% extends 'main/wrapper.html' %}
{% load static %}
{% block content %}
<div class="container py-5">
    <div class="row justify-content-center text-center">
        <div class="col-4">
            <form method="POST">
                {% csrf_token %}
                <div class="form-group text-center">
                    <h3 style="font-weight: bold;">Оставьте отзыв</h3>
                    {{ form }}
                </div>
                <button type="submit" class="btn btn-primary">Добавить Отзыв</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

main/templates/main/feedback_details.html
{% extends 'main/wrapper.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-4 mt-5">
            <div class="shadow-lg p-3 mb-3 bg-info rounded py-3 text-center text-light"
                style="font-family: 'Times New Roman', Times, serif;">
                <h3 class="mb-0"> {{ object.author }} </h3>
            </div>
        </div>
        <div class="col-9">
            <div class="shadow p-4 mt-2 bg-white rounded text-center">
                <em>
                    <h5 class="mb-0">
                        {{ object.feedback_text }}
                    </h5>
                </em>
            </div>
            {% if user.author == user %}
            <div class="col-12 text-center mt-2">
                <a type="button" class="btn btn-primary" style="color: rgb(233, 233, 217);" href="{% url 'main:feedback-update' object.pk%}">Изменить</a>
                <a class="btn btn-dark" style="color:rgb(233, 233, 217);"
                    href="{% url 'main:feedback-delete' object.pk %}">Удалить</a>
            </div>
            {% endif %}
        </div>
        

        <div class="col-12 mt-5 text-center">
            {% if user.is_authenticated %}
            <form method="POST">
                {% csrf_token %}
            <div class="col-5 mx-auto mb-4">
                {{ comment_form }}
                <button type="submit" class='btn btn-success my-3'>Комментировать</button>
            </div>
            </form>
            {% endif %}
            <div class="panel panel-default widget">
                <div class="panel-heading mb-3">
                    <span class="glyphicon glyphicon-comment"></span>
                    <h3 class="panel-title">
                        Последние Комментарии
                    </h3>
                    <h6 class="label label-info">Всего Комментариев: {{user.feedback_set.all|length }}</h6>
                </div>
            </div>
        </div>
        {% for comment in comments %}
        <div class="col-7 text-center">
            <div class="border border-comment_formsuccess rounded-pill my-3 py-3">
                <div class="mb-2">
                    <img src="{{ comment.author.profile_photo.url }}" class="rounded-circle"
                        alt="" width="80px"
                        height="80px" />
                </div>

                <div class="col-12 mb-2">
                    <strong class="mb-3">
                        <em>{{ comment.comment_text }}</em>
                    </strong>
                </div>

                <div class="font-weight-bold">
                    Создано:
                    <em class="text-muted">{{ comment.date_created }}</em>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}


<!-- 

{{ object.date_created|date:"H:i d/j/y"}} -->

main/templates/main/feedback_list.html
{% extends 'main/wrapper.html' %}
{% load static %}

{% block content %}

<div class="container py-5">
    <div class="row justify-content-around">
        {% if user.is_authenticated %}
        <div class="col-3"></div>
        <div class="col-9 text-center mb-5">
            {% else %}
            <div class="col-12 text-center mb-5">
                {% endif %}
                <span class="subheading">
                    <h2>
                        Отзывы
                    </h2>
                </span>
            </div>
            {% if user.is_authenticated %}
            <div class="col-lg-4 col-md-6 col-sm-6 mb-5">
                <div class="card text-center">
                    <div class="mt-2">
                        <h1>{{ user.username }}</h1>
                        <p class="bg-dark w-100 text-light py-2 font-weight-bold">Всего Отзывов:
                            {{user.feedback_set.all|length }}
                        </p>
                        <div class="mb-3">
                            <a type="button" class="btn btn-primary" style="color: whitesmoke;" href="{% url 'main:feedback-create' %}">Оставить Отзыв</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}

            <div class="col-8">
                <div class="row justify-content-center">

                    {% if feedback_list|length > 0 %}
                    {% for feedback in feedback_list %}
                    <div class="col-lg-6 col-md-8 col-sm-12 mb-3">
                        <div class="card text-center" style="height: 300px;">
                            <div class="card-header bg-info pb-1">
                                <p class="font-weight-bold text-light">
                                    {{ feedback.author }}
                                </p>
                            </div>
                            <div class="card-body pb-0">
                                <p class="card-text align-middle">
                                    <em>{{ feedback.feedback_text|truncatechars:100}}</em>
                                </p>
                            </div>
                            <p class="bg-dark w-100 text-light py-1">
                                <strong>{{ feedback.date_created|date:"H:i d/m/Y"}}</strong>
                            </p>
                            <a class="btn btn-outline-info mb-2" href="{% url 'main:feedback-details' feedback.pk %}"
                                style="color: rgb(33, 74, 88);">Читать дальше</a>
                        </div>
                    </div>
                    {% endfor %}
                </div>

                {% endif %}
            </div>
        </div>
    </div>
    {% endblock content %}

main/templates/main/feedback_update.html
{% extends 'main/wrapper.html' %}
{% load static %}
{% block content %}


<div class="container py-5">
    <div class="row justify-content-center text-center">
        <div class="col-4">
            <form method="POST">
                {% csrf_token %}
                <div class="form-group text-center">
                    <h3 style="font-weight: bold;">{{ form.feedback_text.label }}</h3>
                    {{ form.feedback_text }}
                </div>
                <button type="submit" class="btn btn-primary">Изменить Отзыв</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

main/templates/main/wrapper.html
{% load static %}
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{{ title }}</title>
    <meta name="description" content="Resto">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- External CSS -->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/select2/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/owlcarousel/owl.carousel.min.css' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.rawgit.com/noelboss/featherlight/1.7.13/release/featherlight.min.css">

    <!-- Fonts -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700|Josefin+Sans:300,400,700">
    <link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
        integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}">

    <!-- Modernizr JS for IE8 support of HTML5 elements and media queries -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.js"></script>
</head>

<body data-spy="scroll" data-target="#navbar" class="static-layout">
    <div id="side-nav" class="sidenav">
        <a href="javascript:void(0)" id="side-nav-close">&times;</a>

        <div class="sidenav-content">
            <p>
                Kuncen WB1, Wirobrajan 10010, DIY
            </p>
            <p>
                <span class="fs-16 primary-color">(+68) 120034509</span>
            </p>
            <p>info@yourdomain.com</p>
        </div>
    </div>

    <div id="side-search" class="sidenav">
        <a href="javascript:void(0)" id="side-search-close">&times;</a>
        <div class="sidenav-content">
            <form action="">

                <div class="input-group md-form form-sm form-2 pl-0">
                    <input class="form-control my-0 py-1 red-border" type="text" placeholder="Search"
                        aria-label="Search">
                    <div class="input-group-append">
                        <button class="input-group-text red lighten-3" id="basic-text1">
                            <i class="fas fa-search text-grey" aria-hidden="true"></i>
                        </button>
                    </div>
                </div>

            </form>
        </div>
    </div>

    <div id="canvas-overlay"></div>
    <div class="boxed-page">
        <nav id="navbar-header" class="navbar navbar-expand-lg">
            <div class="container">
                <a class="navbar-brand navbar-brand-center d-flex align-items-center p-0 only-mobile"
                    href="{% url 'main:main' %}">
                    <img src="{% static 'img/logo.png' %}" alt="Main Logo">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="lnr lnr-menu"></span>
                </button>

                <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
                    <ul class="navbar-nav d-flex justify-content-between">
                        <li class="nav-item only-desktop">
                            <a class="nav-link" id="side-nav-open" href="#">
                                <span class="lnr lnr-menu"></span>
                            </a>
                        </li>
                        <div class="d-flex flex-lg-row flex-column">
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'main:main' %}">Главная<span
                                        class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'main:about' %}">О нас</a>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Меню
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{% url 'menu:meals' %}">Основные Блюда</a>
                                    <a class="dropdown-item" href="{% url 'menu:wines' %}">Вина</a>
                                </div>
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'main:feedback-list' %}">Отзывы</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'teams:cook-list' %}">Повара</a>
                            </li>
                            </li>
                        </div>
                    </ul>

                    <a class="navbar-brand navbar-brand-center d-flex align-items-center only-desktop"
                        href="{% url 'main:main' %}">
                        <img src="{% static 'img/logo.png' %}" alt="Main Logo">
                    </a>
                    <ul class="navbar-nav d-flex justify-content-between">
                        <div class="d-flex flex-lg-row flex-column">
                            {% if user.is_authenticated %}
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'reservation:orders' %}">Мои Брони<span
                                        class="sr-only">(current)</span></a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'reservation:reservations' %}">Забронировать<span
                                        class="sr-only">(current)</span></a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'logout' %}">Выйти<span
                                        class="sr-only">(current)</span></a>
                            </li>
                            {% else %}
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'login' %}">Войти<span
                                        class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'registration' %}">Регистрация<span
                                        class="sr-only">(current)</span></a>
                            </li>
                            {% endif %}
                        </div>
                        <li class="nav-item">
                            <a id="side-search-open" class="nav-link" href="#">
                                <span class="lnr lnr-magnifier"></span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}{% endblock %}
        <footer class="mastfoot pb-5 bg-white pt-5 pb-0 mt-5" style="border-top:3px solid #b3b3cc;">
            <div class="inner container">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="footer-widget pr-lg-5 pr-0">
                            <img src="{% static 'img/logo.png' %}" class="img-fluid footer-logo mb-3" alt="Main Logo">
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et obcaecati quisquam id sit
                                omnis explicabo voluptate aut placeat, soluta, nisi ea magni facere, itaque incidunt
                                modi? Magni, et voluptatum dolorem.</p>
                            <nav class="nav nav-mastfoot justify-content-start">
                                <a class="nav-link" href="#">
                                    <i class="fab fa-facebook-f"></i>
                                </a>
                                <a class="nav-link" href="#">
                                    <i class="fab fa-twitter"></i>
                                </a>
                                <a class="nav-link" href="#">
                                    <i class="fab fa-instagram"></i>
                                </a>
                            </nav>
                        </div>

                    </div>
                    <div class="col-lg-4">
                        <div class="footer-widget px-lg-5 px-0">
                            <h4>Open Hours</h4>
                            <ul class="list-unstyled open-hours">
                                <li class="d-flex justify-content-between"><span>Monday</span><span>9:00 - 24:00</span>
                                </li>
                                <li class="d-flex justify-content-between"><span>Tuesday</span><span>9:00 - 24:00</span>
                                </li>
                                <li class="d-flex justify-content-between"><span>Wednesday</span><span>9:00 -
                                        24:00</span></li>
                                <li class="d-flex justify-content-between"><span>Thursday</span><span>9:00 -
                                        24:00</span></li>
                                <li class="d-flex justify-content-between"><span>Friday</span><span>9:00 - 02:00</span>
                                </li>
                                <li class="d-flex justify-content-between"><span>Saturday</span><span>9:00 -
                                        02:00</span></li>
                                <li class="d-flex justify-content-between"><span>Sunday</span><span> Closed</span></li>
                            </ul>
                        </div>

                    </div>

                    <div class="col-lg-4">
                        <div class="footer-widget pl-lg-5 pl-0">
                            <h4>Newsletter</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                            <form id="newsletter">
                                <div class="form-group">
                                    <input type="email" class="form-control" id="emailNewsletter"
                                        aria-describedby="emailNewsletter" placeholder="Enter email">
                                </div>
                                <button type="submit" class="btn btn-primary w-100">Submit</button>
                            </form>
                        </div>

                    </div>
                    <div class="col-md-12 d-flex align-items-center">
                        <p class="mx-auto text-center mb-0">Copyright 2019. All Right Reserved. Design by <a
                                href="https://gettemplates.co" target="_blank">GetTemplates</a></p>
                    </div>

                </div>
            </div>
        </footer>
    </div>
    <!-- External JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    <script src="{% static 'vendor/bootstrap/popper.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'vendor/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="https://cdn.rawgit.com/noelboss/featherlight/1.7.13/release/featherlight.min.js"></script>
    <script src="{% static 'vendor/stellar/jquery.stellar.js' %}" type="text/javascript" charset="utf-8"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous"></script>

    <!-- Main JS -->
    <script src="{% static 'js/app.min.js' %}"></script>
</body>

</html>